### ISSUE TITLE
Exception upon install with Windows Store version

### ISSUE THREAD

**Issue by obfuscatedgenerated** [DJCALIEND/LikeADJ#5]
MusicBee version: 3.5.8447 Store
LikeADJ version: 2.0.24

An exception is thrown when installing/enabling the plugin. It looks like the plugin is trying to create a file in the `C:\Program Files\WindowsApps` folder. My user account doesn't have access to this folder, and I believe the Windows Store version uses a folder in `%localappdata%/Packages` for storing data.

![alert box](https://github.com/DJCALIEND/LikeADJ/assets/75035364/d179a682-a171-4615-8eda-1862f9ce91b2)

Full error log:

```
21/09/2023 01:20:47 - 10.0.19045.0 - 3.5.8447.35843 Store - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files\WindowsApps\50072StevenMayall.MusicBee_3.5.8447.0_x86__kcr266et74avj\win32\Plugins\mb_LikeADJ.log' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at MusicBeePlugin.SimpleLogger.WriteLine(String text, Boolean append)
   at MusicBeePlugin.SimpleLogger.WriteFormattedLog(LogLevel level, String text)
   at MusicBeePlugin.Plugin.Initialise(IntPtr apiInterfacePtr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at #=zqR2XciUj1qIekb1OHQ==..ctor(#=zjSxIWkhwlvsm$dC4uw== #=zQB6KZnw=)
```

**Comment by dylan-k** [comment]
I'm also experiencing this issue. Can't activate/use the plugin because of the error. I am not using the Windows Store Version. It's v`3.5.8447`

**Comment by DJCALIEND** [comment]
Hello,

Try the new version 
[2.0.25](https://github.com/DJCALIEND/LikeADJ/blob/master/bin/Debug/mb_LikeADJ.dll?raw=true)

and tell me if the problem is gone.

I use the latest portable version of MusicBee [3.5.8666.27490].

**Comment by obfuscatedgenerated** [comment]
It's fixed for me, thanks a bunch :D
